const activeThreads = new Set();
module.exports.config = {
    name: "chuidenchet",
    version: "1.0.0",
    hasPermssion: 2,
    credits: "",
    description: "chuidenchet người bạn tag (ngôn của mấy đứa war)",
    commandCategory: "War",
    usages: "chuidenchet @mention",
    cooldowns: 10,
    dependencies: {
        "fs-extra": "",
        "axios": ""
    }
}

module.exports.run = async function({ api, args, Users, event }) {
    if (args.length > 0 && args[0] === "stop") {
        if (activeThreads.has(event.threadID)) {
            activeThreads.delete(event.threadID);
            return api.sendMessage("Đã dừng hoạt động của lệnh chuidenchet.", event.threadID);
        } else {
            return api.sendMessage("Lệnh chuidenchet không hoạt động trong nhóm này.", event.threadID);
        }
    }
    const mention = Object.keys(event.mentions)[0];
    if (!mention) return api.sendMessage("Cần phải tag 1 người bạn muốn chửi vào mặt nó", event.threadID);
    const name = event.mentions[mention];
    const arraytag = [{ id: mention, tag: name }];
    activeThreads.add(event.threadID);

    const messages = [
        "Xem Tao Chui Cho Nghe Nay!!",
        "D!t con me may",
        "May ra day tao bao",
        "Hien hon nhanh con cho",
        "Hien hon bo may hoi toi",
        "May tron khi nao moi hien hon day",
        "D!t cu may nua hien hon",
        "Hien hon nhanh khong tao dot nha may gio",
        "Nhanh ra chui nhau voi tao",
        "Tao nem trung thoi do dau do xang vao nha may gio",
        "Con cac dit me may",
        "Deo ra nua bo may dot nha may",
        "Bo may ban rap chet cu may gio",
        "May van deo dam ra a",
        "Vay thi xin moi nghe tao rap dit chet ca lo may nha con",
        "Truoc do cho tao xin nghi 1p nhe",
        "Xin phep mo dau thi",
        "Dau tien tao xin phep dit tu tren xuong duoi con",
        "Tao dit tu lo lon den lo nhi con lon",
        "Lon thi to nhu lon trau thu dam ong cong ay nhe con",
        "Tao dit chac 2 thang nhu tao chua du lap cai lo lon nha may dau",
        "D!t con me may",
        "May ra day tao baoHien hon nhanh con cho",
        "Hien hon nhanh con cho",
        "Hien hon bo may hoi toi",
        "May tron khi nao moi hien hon day",
        "D!t cu may nua hien hon",
        "Hien hon nhanh khong tao dot nha may gio",
        "Dit me may bo noi tu te ma deo day a",
        "Nhanh ra chui nhau voi tao",
        "Con me may ra day di thang lon",
        "Hien hon di thang mat lon",
        "Di me may ra day bo xem nao",
        "Tao nem trung thoi do dau do xang vao nha may gio",
        "Dit me bo goi deo nghe a",
        "Hien ra bo may xem nao",
        "Con cac dit me may",
        "Bo may ban rap chet cu may gio",
        "Vay thi xin moi nghe tao rap dit chet ca lo may nha con",
        "Dau tien tao xin phep dit tu tren xuong duoi con",
        "Tao dit tu lo lon den lo nhi con lon",
        "Lon thi to nhu lon trau thu dam ong cong ay nhe con",
        "Tao dit chac 2 thang nhu tao chua du lap cai lo lon nha may dau",
        "Du con di me may",
        "thang oc cuc",
        "me m de m ra dau lon chu duoc con cac gi",
        "tinh trung khuyet tat",
        "hoi do ba may deo dung bao nen loi ra thang mat cac nhu may do",
        "du di me may",
        "dit con me may",
        "Dit me bo goi deo nghe a",
        "Hoa ra cung chi la con cho mang hinh dang nguoi",
        " Song o doi ma cu nhu He trong rap xiec : ))",
        "May dung so sanh bon tao voi no",
        "vi no la cho con tao la nguoi",
        "May dung bat cuoi khi nghe dieu do",
        "vi ca may va no deu cho nhu nhau",
        "Xa hoi doi mau",
        "Lam nguoi thi kho, lam cho thi de ..!!",
        "Song phai biet nghi",
        "Cuoc song phuc tap, xa hoi bon chen !!",
        " Song ngheo, song kho chu dung song CHO nha con",
        "Cu soi guong nhieu vao",
        "Song - La phai biet dieu",
        " Dung to ve mau lieu nhieu hon mau nao",
        "Thich noi va choi troi tao se cho may len ngoi....",
        "Du ban ma sac may thich thi cu len mam tren ma ngoi!!!",
        "Co dieu may len nho rang.....",
        "Giua cho voi nguoi se chang bao gio co su cong bang.,",
        "Du co co the hien hay la dang nguy bien thi an tuong may chi la 1 tieng ang !!",
        "DIT CON ME!!!",
        "Dop loi bon tao nhu 1 con cho!!!",
        "Con deo nao cung nhu con nao!!!",
        "Hai!!!",
        "Du ma nao cac a",
        "Lich su thi khong co - Chi co cai mau choi cho thi khong ai sanh bang",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "Cai lon",
        "Di me may ra day bo xem nao",
        "Di me may ra day doc cho het",
        "Du con di me may",
        "thang oc cuc",
        "me m de m ra dau lon chu duoc con cac gi",
        "tinh trung khuyet tat",
        "hoi do ba may deo dung bao nen loi ra thang mat cac nhu may do",
        "du di me may",
        "dit con me may",
        "Dit me bo goi deo nghe a",
        "Dit me m ra doc ne",
        "di lon",
        "DIT MEEEEEEEEEE MAY!!!",
        "D!t con me may",
        "May ra day tao bao",
        "Hien hon nhanh con cho",
        "Hien hon bo may hoi toi",
        "May tron khi nao moi hien hon day",
        "D!t cu may nua hien hon",
        "Hien hon nhanh khong tao dot nha may gio",
        "Nhanh ra chui nhau voi tao",
        "Tao nem trung thoi do dau do xang vao nha may gio",
        "Con cac dit me may",
        "Deo ra nua bo may dot nha may",
        "Bo may ban rap chet cu may gio",
        "May van deo dam ra a",
        "Vay thi xin moi nghe tao rap dit chet ca lo may nha con",
        "Tao dit tu lo lon den lo nhi con lon",
        "Lon thi to nhu lon trau thu dam ong cong ay nhe con",
        "Tao dit chac 2 thang nhu tao chua du lap cai lo lon nha may dau",
        "D!t con me may",
        "May ra day tao baoHien hon nhanh con cho",
        "Hien hon nhanh con cho",
        "Hien hon bo may hoi toi",
        "May tron khi nao moi hien hon day",
        "D!t cu may nua hien hon",
        "Hien hon nhanh khong tao dot nha may gio",
        "Dit me may bo noi tu te ma deo day a",
        "Nhanh ra chui nhau voi tao",
        "Con me may ra day di thang lon",
        "Hien hon di thang mat lon",
        "Di me may ra day bo xem nao",
        "Tao nem trung thoi do dau do xang vao nha may gio",
        "Dit me bo goi deo nghe a",
        "Hien ra bo may xem nao",
        "Con cac dit me may",
        "Bo may ban rap chet cu may gio",
        "Vay thi xin moi nghe tao rap dit chet ca lo may nha con",
        "Dau tien tao xin phep dit tu tren xuong duoi con",
        "Tao dit tu lo lon den lo nhi con lon",
        "Lon thi to nhu lon trau thu dam ong cong ay nhe con",
        "Tao dit chac 2 thang nhu tao chua du lap cai lo lon nha may dau",
        "Du con di me may",
        "thang oc cuc",
        "me m de m ra dau lon chu duoc con cac gi",
        "tinh trung khuyet tat",
        "hoi do ba may deo dung bao nen loi ra thang mat cac nhu may do",
        "du di me may",
        "dit con me may",
        "Dit me bo goi deo nghe a",
        "Hoa ra cung chi la con cho mang hinh dang nguoi",
        " Song o doi ma cu nhu He trong rap xiec : ))",
        "May dung so sanh bon tao voi no",
        "vi no la cho con tao la nguoi",
        "May dung bat cuoi khi nghe dieu do",
        "vi ca may va no deu cho nhu nhau",
        "Xa hoi doi mau",
        "Lam nguoi thi kho, lam cho thi de ..!!",
        "Song phai biet nghi",
        "Cuoc song phuc tap, xa hoi bon chen !!",
        " Song ngheo, song kho chu dung song CHO nha con",
        "Cu soi guong nhieu vao",
        "Song - La phai biet dieu",
        " Dung to ve mau lieu nhieu hon mau nao",
        "Thich noi va choi troi tao se cho may len ngoi....",
        "Du ban ma sac may thich thi cu len mam tren ma ngoi!!!",
        "Co dieu may len nho rang.....",
        "Giua cho voi nguoi se chang bao gio co su cong bang.,",
        "Du co co the hien hay la dang nguy bien thi an tuong may chi la 1 tieng ang !!",
        "DIT CON ME!!!",
        "Dop loi bon tao nhu 1 con cho!!!",
        "Con deo nao cung nhu con nao!!!",
        "Hai!!!",
        "Du ma nao cac a",
        "Lich su thi khong co - Chi co cai mau choi cho thi khong ai sanh bang",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "Cai lon",
        "Di me may ra day bo xem nao",
        "Di me may ra day doc cho het",
        "Du con di me may",
        "thang oc cuc",
        "me m de m ra dau lon chu duoc con cac gi",
        "tinh trung khuyet tat",
        "hoi do ba may deo dung bao nen loi ra thang mat cac nhu may do",
        "du di me may",
        "dit con me may",
        "Dit me bo goi deo nghe a",
        "Dit me m ra doc ne",
        "di lon",
        "DIT MEEEEEEEEEE MAY!!!",
        "D!t con me may",
        "May ra day tao bao",
        "Hien hon nhanh con cho",
        "Hien hon bo may hoi toi",
        "May tron khi nao moi hien hon day",
        "D!t cu may nua hien hon",
        "Hien hon nhanh khong tao dot nha may gio",
        "Nhanh ra chui nhau voi tao",
        "Tao nem trung thoi do dau do xang vao nha may gio",
        "Deo ra nua bo may dot nha may",
        "Bo may ban rap chet cu may gio",
        "May van deo dam ra a",
        "Vay thi xin moi nghe tao rap dit chet ca lo may nha con",
        "Tao dit tu lo lon den lo nhi con lon",
        "Lon thi to nhu lon trau thu dam ong cong ay nhe con",
        "Tao dit chac 2 thang nhu tao chua du lap cai lo lon nha may dau",
        "D!t con me may",
        "May ra day tao baoHien hon nhanh con cho",
        "Hien hon nhanh con cho",
        "Hien hon bo may hoi toi",
        "May tron khi nao moi hien hon day",
        "D!t cu may nua hien hon",
        "Hien hon nhanh khong tao dot nha may gio",
        "Dit me may bo noi tu te ma deo day a",
        "Nhanh ra chui nhau voi tao",
        "Con me may ra day di thang lon",
        "Hien hon di thang mat lon",
        "Di me may ra day bo xem nao",
        "Tao nem trung thoi do dau do xang vao nha may gio",
        "Dit me bo goi deo nghe a",
        "Hien ra bo may xem nao",
        "Con cac dit me may",
        "Bo may ban rap chet cu may gio",
        "Vay thi xin moi nghe tao rap dit chet ca lo may nha con",
        "Dau tien tao xin phep dit tu tren xuong duoi con",
        "Tao dit tu lo lon den lo nhi con lon",
        "Lon thi to nhu lon trau thu dam ong cong ay nhe con",
        "Tao dit chac 2 thang nhu tao chua du lap cai lo lon nha may dau",
        "Du con di me may",
        "thang oc cuc",
        "me m de m ra dau lon chu duoc con cac gi",
        "tinh trung khuyet tat",
        "hoi do ba may deo dung bao nen loi ra thang mat cac nhu may do",
        "du di me may",
        "dit con me may",
        "Dit me bo goi deo nghe a",
        "Hoa ra cung chi la con cho mang hinh dang nguoi",
        " Song o doi ma cu nhu He trong rap xiec : ))",
        "May dung so sanh bon tao voi no",
        "vi no la cho con tao la nguoi",
        "May dung bat cuoi khi nghe dieu do",
        "vi ca may va no deu cho nhu nhau",
        "Xa hoi doi mau",
        "Lam nguoi thi kho, lam cho thi de ..!!",
        "Song phai biet nghi",
        "Cuoc song phuc tap, xa hoi bon chen !!",
        " Song ngheo, song kho chu dung song CHO nha con",
        "Cu soi guong nhieu vao",
        "Song - La phai biet dieu",
        " Dung to ve mau lieu nhieu hon mau nao",
        "Thich noi va choi troi tao se cho may len ngoi....",
        "Du ban ma sac may thich thi cu len mam tren ma ngoi!!!",
        "Co dieu may len nho rang.....",
        "Giua cho voi nguoi se chang bao gio co su cong bang.,",
        "Du co co the hien hay la dang nguy bien thi an tuong may chi la 1 tieng ang !!",
        "DIT CON ME!!!",
        "Dop loi bon tao nhu 1 con cho!!!",
        "Con deo nao cung nhu con nao!!!",
        "Hai!!!",
        "Du ma nao cac a",
        "Lich su thi khong co - Chi co cai mau choi cho thi khong ai sanh bang",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "thang mat cac",
        "thang nao lon",
        "Cai lon",
        "Di me may ra day bo xem nao",
        "Di me may ra day doc cho het",
        "Du con di me may",
        "thang oc cuc",
        "me m de m ra dau lon chu duoc con cac gi",
        "tinh trung khuyet tat",
        "hoi do ba may deo dung bao nen loi ra thang mat cac nhu may do",
        "du di me may",
        "dit con me may",
        "Dit me bo goi deo nghe a",
        "Dit me m ra doc ne",
        "di lon",
        "DIT MEEEEEEEEEE MAY!!!",
        "tam biet may con di",
        "bo may di lam viec co ich cho xa hoi",
        "deo o lai noi chuyen moi may dua ngu nhu may",
        "can than ti acc fb may deo con nha",
        "gio thi bye",
        "may tuong xong roi a deo co dau nam mo di con tinh trung khuyet tat",
        "dit cai lon me may con cho suc sinh vat hoc nay deo ai day may gap nguoi lon phai le phep a",
        "cai con di dau trau mat nguoi nay bo may tuong cai buoi vao mom may cho may bot noi nhe",
        "a ma quen thu suc vat nhu may thi deo co cua ma ngam cac tao",
        "Dong thu ngu nguc ma cu to ve ta day thuong dang, can than cai mom khong la deo co cai rang nhai com",
        "bo me thi lam chet con di me dau co biet con pho ha thien lon nhu may o nha xam cac nhu nay",
        "thu cua may thi bot len mang xam lon o nha dang hang lam lon cong cong kiem tien bao hieu cha me con kip con di a",
        "ba gia may vi mot phut nung lon nhung lai deo co trach nhiem moi lai sanh ra thu nhu may roi deo biet day may",
        "tha ong ba de trung ga trung vit an con co y nghia hon la dau lon dai ra thu nhu may",
        "Kiem moi lon nguoi roi nhe hong con ha ba suc vat quai thai",
        "Dit con me lan sau con ham lon nhu nay thi bo may lay cu gia tat vao lon cho may tinh ngo nghe chua",
        "cai lon me may noi nhe noi khe thi deo nghe phai di cai lon vao mat may thi moi chiu tinh",
        "thu am binh dau thai ma lai bu cac ngua",
        "Nung lon it thoi nghe chua con di cho",
        "Con gio thi tien vong ve am tao dia phu di suc vat",
        "BYE MAY CON LONNNNNNNNMNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"
    ];

    const sendMessages = () => {
        for (let i = 0; i < messages.length; i++) {
            setTimeout(() => {
                if (activeThreads.has(event.threadID)) {
                    api.sendMessage({ body: messages[i] + " " + name, mentions: arraytag }, event.threadID);
                }
            }, i * 5000);
        }
    };

    sendMessages();
};
