let isVideocosplayEnabled = true;
module.exports.config = {
  name: "videocosplay",
  version: "1.0.1",
  hasPermssion: 0,
  credits: "includes",
  description: "chỉ cần nhắn video cosplay, Vdcos ",
  commandCategory: "Video",
  usages: "chỉ cần nhắn video cosplay, Vdcos ",
  cooldowns: 0,
  denpendencies: {
    "fs-extra": "",
    "request": ""
  }

};
module.exports.handleEvent = async ({ api, event, Threads }) => {
if (!isVideocosplayEnabled) return;
  if (event.body.indexOf("video cosplay")==0 || (event.body.indexOf("Video cosplay")==0) || 
event.body.indexOf("Vdcos")==0) {
    const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];

    api.sendMessage("Hình như bạn muốn xem gái cosplay\nChờ mình một chút nha.", event.threadID, event.messageID);

    var link = [
"https://i.imgur.com/YoTbz4d.mp4",
"https://i.imgur.com/097B6D8.mp4",
"https://i.imgur.com/xrCInYm.mp4",
"https://i.imgur.com/GG6YPqe.mp4",
"https://i.imgur.com/agVVYx5.mp4",
"https://i.imgur.com/o8ao6XY.mp4",
"https://i.imgur.com/bbh1V26.mp4",
"https://i.imgur.com/S8ISdD6.mp4",
"https://i.imgur.com/pauY8KR.mp4",
"https://i.imgur.com/9hfEbGH.mp4",
"https://i.imgur.com/72bYCsn.mp4",
"https://i.imgur.com/I3NJ05u.mp4",
"https://i.imgur.com/B5U6d33.mp4",
"https://i.imgur.com/jUG4eIz.mp4",
"https://i.imgur.com/CGB6XmV.mp4",
"https://i.imgur.com/KZNijRx.mp4",
    "https://i.imgur.com/ANDGPv4.mp4",
      "https://i.imgur.com/hpDI3bw.mp4",
      "https://i.imgur.com/stcqzUk.mp4",
      "https://i.imgur.com/UxuJOTJ.mp4",
      "https://i.imgur.com/lQcXTch.mp4",
      "https://i.imgur.com/hMsIAvn.mp4",
      "https://i.imgur.com/HmcPhLC.mp4",
      "https://i.imgur.com/aKt47k0.mp4",
      "https://i.imgur.com/vmisIKs.mp4",
      "https://i.imgur.com/842S5AA.mp4",
      "https://i.imgur.com/DU0xNJ5.mp4",
      "https://i.imgur.com/1tgx5tI.mp4",
      "https://i.imgur.com/Q73D1LX.mp4",
      "https://i.imgur.com/VSh7JWQ.mp4",
      "https://i.imgur.com/IC73HJ9.mp4",
      "https://i.imgur.com/gvjAKox.mp4",
      "https://i.imgur.com/0tnC4LM.mp4",
      "https://i.imgur.com/75A44i9.mp4",
      "https://i.imgur.com/lZQN04e.mp4",
      "https://i.imgur.com/lOpisyj.mp4",
      "https://i.imgur.com/O320FUs.mp4",
      "https://i.imgur.com/k3oZRL5.mp4",
      "https://i.imgur.com/9I0PQID.mp4",
      "https://i.imgur.com/jRmwCwc.mp4",
      "https://i.imgur.com/FdOpSWr.mp4",
      "https://i.imgur.com/hF716fC.mp4",
      "https://i.imgur.com/14XJi6K.mp4",
      "https://i.imgur.com/iCksjMW.mp4",
      "https://i.imgur.com/Go7JQVO.mp4",
      "https://i.imgur.com/EQSRSLo.mp4",
      "https://i.imgur.com/JNJvrnS.mp4",
      "https://i.imgur.com/Bqx2xGM.mp4",
      "https://i.imgur.com/FxOq0OH.mp4",
      "https://i.imgur.com/Povo7aG.mp4",
      "https://i.imgur.com/mX8kJl6.mp4",
      "https://i.imgur.com/UoIywkq.mp4",
      "https://i.imgur.com/3OSRb1N.mp4",
      "https://i.imgur.com/SH08EvT.mp4",
      "https://i.imgur.com/RymLgq8.mp4",
      "https://i.imgur.com/IJUnurS.mp4",
      "https://i.imgur.com/3hnWCyC.mp4",
      "https://i.imgur.com/vEcFQwc.mp4",
      "https://i.imgur.com/mq6brRE.mp4",
      "https://i.imgur.com/YdAf6O3.mp4",
      "https://i.imgur.com/obCzZUO.mp4",
      "https://i.imgur.com/0QTxCnD.mp4",
      "https://i.imgur.com/t3oIe9s.mp4",
      "https://i.imgur.com/c3wieTA.mp4",
      "https://i.imgur.com/sFr9cDT.mp4",
      "https://i.imgur.com/qK1hoD5.mp4",
      "https://i.imgur.com/t8XxwRF.mp4",
      "https://i.imgur.com/y2aK7rX.mp4",
      "https://i.imgur.com/cMotfW4.mp4",
      "https://i.imgur.com/namsDPk.mp4",
      "https://i.imgur.com/z0VLtIM.mp4",
      "https://i.imgur.com/PrMkk8U.mp4",
      "https://i.imgur.com/JUG7s5Q.mp4",
      "https://i.imgur.com/1sFSDkv.mp4",
      "https://i.imgur.com/WwVviiO.mp4",
      "https://i.imgur.com/k3NeFB9.mp4",
      "https://i.imgur.com/zu7TZnT.mp4",
      "https://i.imgur.com/1mSpgCN.mp4",
      "https://i.imgur.com/VlsYtvA.mp4",
      "https://i.imgur.com/BuA4QYr.mp4",
      "https://i.imgur.com/GzD1xIU.mp4",
      "https://i.imgur.com/2VyifK2.mp4",
      "https://i.imgur.com/0Rwb0w1.mp4",
      "https://i.imgur.com/360Fm6X.mp4",
      "https://i.imgur.com/RuLS9Hj.mp4",
      "https://i.imgur.com/74w41Jm.mp4",
      "https://i.imgur.com/kxih52q.mp4",
      "https://files.catbox.moe/scqifh.mp4",
      "https://files.catbox.moe/2qn663.mp4",
      "https://files.catbox.moe/p3fdik.mp4",
      "https://files.catbox.moe/fej6g3.mp4",
      "https://files.catbox.moe/ukg2st.mp4",
      "https://files.catbox.moe/xrylxp.mp4",
      "https://files.catbox.moe/7dir7g.mp4",
      "https://files.catbox.moe/szf364.mp4",
      "https://files.catbox.moe/8t2tfz.mp4",
      "https://files.catbox.moe/nplg4a.mp4",
      "https://files.catbox.moe/nijfol.mp4",
      "https://files.catbox.moe/yjff9k.mp4",
      "https://files.catbox.moe/6zy3z2.mp4",
      "https://files.catbox.moe/28zf3a.mp4",
      "https://files.catbox.moe/71f8ap.mp4",
      "https://files.catbox.moe/leit50.mp4",
      "https://files.catbox.moe/p46d19.mp4",
      "https://files.catbox.moe/1moa0i.mp4",
      "https://files.catbox.moe/xkyuts.mp4",
      "https://files.catbox.moe/fl9qsv.mp4",
      "https://files.catbox.moe/e37p7l.mp4",
      "https://files.catbox.moe/wvqjg1.mp4",
      "https://files.catbox.moe/4t04vj.mp4",
      "https://files.catbox.moe/6t4wp7.mp4",
      "https://files.catbox.moe/im8atv.mp4",
      "https://files.catbox.moe/42lnoz.mp4",
      "https://files.catbox.moe/9zoqn1.mp4",
      "https://files.catbox.moe/pbqemw.mp4",
      "https://files.catbox.moe/j2yq2v.mp4",
      "https://files.catbox.moe/22od6k.mp4",
      "https://files.catbox.moe/6lwscp.mp4",
      "https://files.catbox.moe/f9g5fv.mp4",
      "https://files.catbox.moe/e50pva.mp4",
      "https://files.catbox.moe/k351o6.mp4",
      "https://files.catbox.moe/0i468x.mp4",
      "https://files.catbox.moe/3pjxjf.mp4",
      "https://files.catbox.moe/tnu26i.mp4",
      "https://files.catbox.moe/cw2imd.mp4",
      "https://files.catbox.moe/5vufsr.mp4",
      "https://files.catbox.moe/b3zrvv.mp4",
      "https://files.catbox.moe/1wkt8s.mp4",
      "https://files.catbox.moe/0rpv1i.mp4",
      "https://files.catbox.moe/yypd38.mp4",
      "https://files.catbox.moe/7124bh.mp4",
      "https://files.catbox.moe/8b9c69.mp4",
      "https://files.catbox.moe/8hhkqt.mp4",
      "https://files.catbox.moe/6tve29.mp4",
      "https://files.catbox.moe/6pb5ap.mp4",
      "https://files.catbox.moe/wv2lym.mp4",
      "https://files.catbox.moe/ca8997.mp4",
      "https://i.imgur.com/F4ZpRIN.mp4",
      "https://files.catbox.moe/w9i8je.mp4",
      "https://files.catbox.moe/y6rxig.mp4",
      "https://files.catbox.moe/dnb97s.mp4",
      "https://files.catbox.moe/6yxbke.mp4",
      "https://files.catbox.moe/wtlul3.mp4",
      "https://files.catbox.moe/7f9xi7.mp4",
      "https://files.catbox.moe/dr06pg.mp4",
      "https://files.catbox.moe/n0or7n.mp4",
      "https://files.catbox.moe/56as9n.mp4",
      "https://files.catbox.moe/i3wn40.mp4",
      "https://files.catbox.moe/raen78.mp4",
      "https://files.catbox.moe/j2bfvm.mp4",
      "https://files.catbox.moe/09znro.mp4",
      "https://files.catbox.moe/1ihpyg.mp4",
      "https://files.catbox.moe/n4weh3.mp4",
      "https://files.catbox.moe/5aqltt.mp4",
      "https://files.catbox.moe/rlvw7h.mp4",
      "https://files.catbox.moe/rmd3f9.mp4",
      "https://files.catbox.moe/ocvk3o.mp4",
      "https://files.catbox.moe/ikwd2c.mp4",
      "https://files.catbox.moe/do77ce.mp4",
      "https://files.catbox.moe/612h7p.mp4",
      "https://files.catbox.moe/bkhu9q.mp4",
      "https://files.catbox.moe/4s1u7e.mp4",
      "https://files.catbox.moe/44cfph.mp4",
      "https://files.catbox.moe/4k2vch.mp4",
      "https://files.catbox.moe/ve6dws.mp4",
      "https://files.catbox.moe/yjsuuk.mp4",
      "https://files.catbox.moe/gp3eps.mp4",
      "https://files.catbox.moe/8y7l97.mp4",
      "https://files.catbox.moe/1ndsni.mp4",
      "https://files.catbox.moe/cqq28g.mp4",
      "https://files.catbox.moe/y3iy02.mp4",
      "https://files.catbox.moe/oqawns.mp4",
      "https://files.catbox.moe/a6cdsm.mp4",
      "https://files.catbox.moe/bnbxvd.mp4",
      "https://files.catbox.moe/df85nq.mp4",
      "https://files.catbox.moe/h6q3ym.mp4",
      "https://files.catbox.moe/7c1hj0.mp4",
      "https://files.catbox.moe/x4lg4r.mp4",
      "https://files.catbox.moe/jvau6x.mp4"
];
     var callback = () => api.sendMessage({body:`Số video hiện có: ${link.length}`,attachment: fs.createReadStream(__dirname + "/cache/vdcos.mp4")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/vdcos.mp4"), event.messageID);  
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/vdcos.mp4")).on("close",() => callback());
}
                                                                                                         };
module.exports.run = async ({ api, event, args }) => {
  if (args[0] === "on") {
    isVideocosplayEnabled = true;
    api.sendMessage("Tự động gửi video cosplay khi nhắn 'video cosplay, Vdcos' đã được bật.", event.threadID, event.messageID);
  } else if (args[0] === "off") {
    isVideocosplayEnabled = false;
    api.sendMessage("Tự động gửi video cosplay khi nhắn 'video cosplay, Vdcos' đã được tắt.", event.threadID, event.messageID);
  } else {
    api.sendMessage("Sử dụng: /videocosplay on hoặc /videocosplay off", event.threadID, event.messageID);
  }
};